### ISSUE TITLE
Spellblade should be summonable, and returnable, or just returnable like ninja

### ISSUE THREAD

**Issue by Hmeister-real** [Verbalase/Goob-Station#78]
## Description
Maybe it should automatically return after being ropped to stop wizards from slipping, and then getting stabbed 20 times by the tider following them. But even just the option to dispell their sword would be great cause i've seen it get stolen a lot, or at least returned to them (recyclable from ninja code?)

**Comment by Verbalase** [comment]
is this an issue or suggestion

**Comment by Hmeister-real** [comment]
> is this an issue or suggestion

both

**Comment by Verbalase** [comment]
> > is this an issue or suggestion
> 
> both

Sounds more like a [suggestion](https://x329436.invisionservice.com/forum/16-suggestions/).
